# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'FriendBNB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FriendBNB
  pod 'FirebaseAuth'
  pod 'FirebaseCore'
  pod 'SwiftLint'

#  target 'FriendBNBTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'FriendBNBUITests' do
#    # Pods for testing
#  end

end
