# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'FriendBNB' do
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!
inhibit_all_warnings!

# Pods for FriendBNB
pod 'FirebaseAuth'
pod 'FirebaseFirestore' , '~> 10.0'
pod 'FirebaseDynamicLinks'
pod 'FirebaseMessaging'
pod 'SwiftLint'

#  target 'FriendBNBTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'FriendBNBUITests' do
#    # Pods for testing
#  end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
  end
 end
end

end
